### PR TITLE
Removing attribute type in YAML, in order to make it cleaner and more flexible

### PR DESCRIPTION
**Pull request by Duerno**

### CODE REVIEW

**Comment by diegodorgam** [comment]
interesting, you're proposing to remove `type` attribute to use a YAML notation where one line of response could have a new structure of levels for multiple responses.
Is that right?

**Comment by Duerno** [comment]
Yes. The main idea is that you have a list of answers and the bot will choose one of them randomly. Each answer can be a single message or a list of messages (previously called 'block' messages). Each message (string) may have multiple lines by using de default YAML syntax (with `|` and `>`, as described in [YAML Multiline Strings](http://yaml-multiline.info/)).

**Comment by diegodorgam** [comment]
@Duerno we have some problems with your commits, just merged another one that changes some structure conventions.
Can you take a look?

**Comment by Duerno** [comment]
@diegodorgam I've rebased my commit with origin/master and updated the structure conventions.

**Pull request merged**
